import '../infra.recipes.just'

# Default recipe - show available commands
help:
  just --list

# Initialize Terraform (global stack)
[group('init')]
init env="local" +args="":
  terraform init --reconfigure --backend-config=.config.{{env}}.tfbackend {{args}}

# Clean up
[group('init')]
clean:
  rm -rf .terraform
  rm -rf .terraform.lock.hcl
