# Infrastructure management recipes

# Bootstrap stack
[group('stacks')]
mod bootstrap

# Global stack
[group('stacks')]
mod global

# Services stack
[group('stacks')]
mod services

# Default recipe - show available commands
help:
  just --list

# Start LocalStack
[group('localstack')]
localstack-start:
  docker compose up -d

# Stop LocalStack
[group('localstack')]
localstack-stop:
  docker compose down

# Status LocalStack
[group('localstack')]
localstack-status:
  docker compose ps
